### ISSUE TITLE
About the input of 

### ISSUE THREAD

**Issue by chingyaoc** [akirafukui/vqa-mcb#1]
From line 66 to 69 in `train/multi_att_2_glove/train_att_bc.py` 

```
n.q_emb_tanh_droped_resh = L.Reshape(n.lstm_12,reshape_param=dict(shape=dict(dim=[-1,2048,1,1])))
n.q_emb_tanh_droped_resh_tiled_1 = L.Tile(n.q_emb_tanh_droped_resh, axis=2, tiles=14)
n.q_emb_tanh_droped_resh_tiled = L.Tile(n.q_emb_tanh_droped_resh_tiled_1, axis=3, tiles=14)
n.i_emb_tanh_droped_resh = L.Reshape(n.img_feature,reshape_param=dict(shape=dict(dim=[-1,2048,14,14])))
n.blcf = L.CompactBilinear(n.q_emb_tanh_droped_resh_tiled, n.i_emb_tanh_droped_resh, compact_bilinear_param=dict(num_output=16000,sum_pool=False))
```

It seems that the input for MCB is (batch_size,2048,14,14) which make me confuse.
I thought that the inputs should be one dimensional vector like (batch_size,2048).

**Comment by daylen** [comment]
That's right, the MCB takes in two (batch_size, 2048, 14, 14) blobs and outputs a (batch_size, 16000, 14, 14) blob. It's taking the compressed outer product of the two 2048-D vectors in each spatial location.

**Comment by chingyaoc** [comment]
OHH I got it, thanks a lot!
