### ISSUE TITLE
can I use Compact Bilinear layers on torch

### ISSUE THREAD

**Issue by cloud-waiting-for-wind** [akirafukui/vqa-mcb#11]
If I have caffemodel and prototxt,  is it possible to use MCB layer on torch? Is there any problem when backforward through MCB layer?

**Comment by jnhwkim** [comment]
@cloud-waiting-for-wind you can try this module: https://github.com/jnhwkim/cbp

**Comment by cloud-waiting-for-wind** [comment]
thank you!
