### ISSUE TITLE
error in ensemble.py:  Unknown bottom blob 'glove' (layer 'concat_embed', bottom index 1)

### ISSUE THREAD

**Issue by suhmily** [akirafukui/vqa-mcb#12]
When I tried to evaluate the pre-trained model by running
python ensemble.py ---ques_file 'vqa_eval/Questions/OpenEnded_mscoco_val2014_questions.json' --gpu 0 --folders ['./multi_att_2_glove_pretrained']
I used the aux.json file in "multi_att_2_glove_pretrained" that I downloaded from github.
I got an error:
F0113 19:20:49.447276  3179 insert_splits.cpp:29] Unknown bottom blob 'glove' (layer 'concat_embed', bottom index 1)
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by Seth-Park** [comment]
Can you explain exactly what command you entered and how the aux.json file looks like?

**Comment by suhmily** [comment]
The command I entered is 
python ensemble.py ---ques_file 'vqa_eval/Questions/OpenEnded_mscoco_val2014_questions.json' --gpu 0 --folders ['./multi_att_2_glove_pretrained']
I used the aux.json file in "multi_att_2_glove_pretrained" that I downloaded from github.

**Comment by Seth-Park** [comment]
Hmm.. Did you install Spacy and download Glove Vectors correctly? Also make sure that you've compiled Caffe with PythonLayer support.

**Comment by mrfarazi** [comment]
Hello @suhmily / @Seth-Park , How did you fix this problem and can you please provide the syntax/command you used for the ensemble.py script? I am getting an error for unrecognised arguments for the 'folders' option
