### ISSUE TITLE
F0715 11:06:40.520928 65172 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: SoftAttention

### ISSUE THREAD

**Issue by mrfarazi** [akirafukui/vqa-mcb#15]
Hello @daylen @Seth-Park 

I am trying to run the `train_att_bc.py` code in `multi_att_2_glove`. After it has parsed the question and answer vocabulary, I am getting the following error

```
I0715 11:06:40.520900 65172 layer_factory.hpp:77] Creating layer att_feature0
F0715 11:06:40.520928 65172 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: SoftAttention (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, CompactBilinear, Concat, ContrastiveLoss, Convolution, Crop, Data, Deconvolution, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, Input, L2Normalize, LRN, LSTM, LSTMUnit, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Parameter, Pooling, Power, Python, RNN, ReLU, Reduction, Reshape, SPP, Scale, Sigmoid, SigmoidCrossEntropyLoss, SignedSqrt, Silence, Slice, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, Tile, WindowData)
*** Check failure stack trace: ***
Aborted
```

I am using
- `feature/20160617_cb_softattention` branch of your caffe fork
- caffe build with python LayerSupport
- python 2.7
- spacy with en
- cudnn/v6 cuda/8.0.61

I would really appreciate your input in this matter.

**Comment by daylen** [comment]
You should double check that you're using the right branch of our Caffe fork. It's not enough to check out that repo, you need to explicitly do `git checkout feature/20160617_cb_softattention` and verify that `git log` shows the latest commits to that branch. Finally, make sure your paths are set correctly to point to this fork.

**Comment by AgarwalVedika** [comment]
I have compiled this specific branch, but I am still getting the same error..
