### ISSUE TITLE
I get shape error when I run the server

### ISSUE THREAD

**Issue by minsuu** [akirafukui/vqa-mcb#2]
I've installed all the proper dependencies, including custom version caffe, etc...
But when I try to run `server.py`, I get this error after uploading the image:

```
File "server.py", line 159, in upload_image
    resnet_net.blobs['data'].data[0,...] = preprocessed_img
ValueError: could not broadcast input array from shape (3,448,448) into shape (3,224,224)
```

my `ResNet-152-deploy.prototxt` states that input dimension is `3*224*224`.. but I think `server.py` is giving `3*448*448` data to ResNet. How can I correct this?

**Comment by minsuu** [comment]
I replaced the value of `RESNET_MEAN_PATH` and`RESNET_LARGE_PROTOTXT_PATH` with `preprocess/ResNet_mean.binaryproto` and `preprocess/ResNet-152-448-deploy.prototxt`, not the mean/prototxts in [pretrained model](https://github.com/KaimingHe/deep-residual-networks) and it worked well!

**Comment by MILOTIDE** [comment]
Hello.I have set all the path correctly (RESNET_MEAN_PATH and RESNET_LARGE_PROTOTXT_PATH) but got the error:
  File " /vqa-mcb/vqa-mcb-master/server/vqa_data_provider_layer.py", line 125, in qlist_to_vec
    glove_matrix[i] = self.glove_dict[w]
ValueError: could not broadcast input array from shape (384) into shape (300).
Can u give me some advice ?
Thank u very much.

**Comment by MILOTIDE** [comment]
@minsuu @daylen
