### ISSUE TITLE
One of the tests fails for CompactBilinearLayer

### ISSUE THREAD

**Issue by kushalkafle** [akirafukui/vqa-mcb#3]
I successfully built the caffe-feature-20160617_cb_softattention branch. But one of the tests fail. I wanted to draw your attention to that. All other tests for the Compact Bilinear Layer works fine except for that one.

`[  FAILED  ] CompactBilinearLayerTest/0.TestGradientBottomDiff, where TypeParam = caffe::CPUDevice<float> (9 ms)
[ RUN      ] CompactBilinearLayerTest/0.TestSetUp
[       OK ] CompactBilinearLayerTest/0.TestSetUp (2 ms)
[ RUN      ] CompactBilinearLayerTest/0.TestGradientBottomSameNoPool
[       OK ] CompactBilinearLayerTest/0.TestGradientBottomSameNoPool (8 ms)
[ RUN      ] CompactBilinearLayerTest/0.TestSpeed
[       OK ] CompactBilinearLayerTest/0.TestSpeed (125 ms)
[ RUN      ] CompactBilinearLayerTest/0.TestGradientBottomDiffNoPool
[       OK ] CompactBilinearLayerTest/0.TestGradientBottomDiffNoPool (9 ms)
[ RUN      ] CompactBilinearLayerTest/0.TestGradientBottomSame
[       OK ] CompactBilinearLayerTest/0.TestGradientBottomSame (8 ms)
[----------] 6 tests from CompactBilinearLayerTest/0 (161 ms total)
`

**Comment by BAILOOL** [comment]
Same here

[  FAILED  ] 2 tests, listed below:
[  FAILED  ] CompactBilinearLayerTest/0.TestGradientBottomSameNoPool, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] CompactBilinearLayerTest/2.TestGradientBottomSameNoPool, where TypeParam = caffe::GPUDevice<float>

**Comment by Seth-Park** [comment]
We have verified that the testing script for the Compact Bilinear Layer has a bug, not the actual implementation. We will make a pull request to the Compact Bilinear branch to address this issue in the near future. In the meantime, you may proceed to using the Compact Bilinear Layer without worrying about the test results. Sorry for the confusion and thank you for pointing this out.
