### ISSUE TITLE
where is normalization for image feature?

### ISSUE THREAD

**Issue by jnhwkim** [akirafukui/vqa-mcb#5]
Figure 3 in Fukui et al. (2016) depicts that L2 normalization is applied after CNN, however, I cannot locate the normalization in the code.

Am I missed somewhere?

**Comment by daylen** [comment]
L2 normalization of the image feature is located here: https://github.com/akirafukui/vqa-mcb/blob/master/train/multi_att_2_glove/vqa_data_provider_layer.py#L230

**Comment by jnhwkim** [comment]
@daylen Thanks! This code l2-normalizes over 2048x14x14, right?

**Comment by daylen** [comment]
Yes.
