### ISSUE TITLE
How to get 2048d vector for the images?

### ISSUE THREAD

**Issue by zhuchen03** [akirafukui/vqa-mcb#8]
I think the code provided in preprocess folder extracts only the 14x14x2048 feature maps from the images, but in the v4 model, we should provide a 2048d vector image from each image. The paper also did not say it clearly how we should get this 2048d vector from resnet.

So how did you do it?

**Comment by daylen** [comment]
In `preprocess/config.py`, change references to `res5c` to `pool5`, and change `EXTRACT_LAYER_SIZE` to `(2048)`. Then run the preprocessing script.
